// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP9TCUfhbX4El_J3EmAZ07Ci6lrbeQLVM',
    appId: '1:864002706269:web:43d38fa19b9f44ba7b36b4',
    messagingSenderId: '864002706269',
    projectId: 'mrchat-8c73b',
    authDomain: 'mrchat-8c73b.firebaseapp.com',
    storageBucket: 'mrchat-8c73b.firebasestorage.app',
    measurementId: 'G-C0WKJH1CHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzmFxWbGB18s4Nc7olPizXhLqR1BozYk',
    appId: '1:864002706269:android:0b92434ea3bc55247b36b4',
    messagingSenderId: '864002706269',
    projectId: 'mrchat-8c73b',
    storageBucket: 'mrchat-8c73b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxN9OSuxJYDMqePiSyINYecssv3LDALM4',
    appId: '1:864002706269:ios:98561540b2088fc77b36b4',
    messagingSenderId: '864002706269',
    projectId: 'mrchat-8c73b',
    storageBucket: 'mrchat-8c73b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxN9OSuxJYDMqePiSyINYecssv3LDALM4',
    appId: '1:864002706269:ios:98561540b2088fc77b36b4',
    messagingSenderId: '864002706269',
    projectId: 'mrchat-8c73b',
    storageBucket: 'mrchat-8c73b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP9TCUfhbX4El_J3EmAZ07Ci6lrbeQLVM',
    appId: '1:864002706269:web:e6aa6102c88dcfa27b36b4',
    messagingSenderId: '864002706269',
    projectId: 'mrchat-8c73b',
    authDomain: 'mrchat-8c73b.firebaseapp.com',
    storageBucket: 'mrchat-8c73b.firebasestorage.app',
    measurementId: 'G-MHT495GVP1',
  );
}
